### ISSUE TITLE
RethinkDB image status?

### ISSUE THREAD

**Issue by ulm0** [pdonorio/dockerizing#1]
Hello, looking for a rethinkdb image based on alpine i found [this thread](https://github.com/rethinkdb/rethinkdb/issues/4437) on the db repo, and you said you were working on something like that using [your Dockerfile](https://github.com/pdonorio/dockerizing/blob/master/databases/rethinkdb_tiny/Dockerfile), is it working? i want to give it a try to build it for ARM.

**Comment by pdonorio** [comment]
Hello @klud1,
as you saw on the thread that one was my first and only attempt. 
I was waiting for a reply to get hints on how to proceed, and still waiting.

If you want to try and dig further we can work together with this issue, I'll also ping on that issue.

I personally use now the official `rethinkdb:2.3.5` image for now.

**Comment by ulm0** [comment]
Ya, i saw they closed the issue after your comment as well.
Sure, that'd be great, i want to build it for arm for now since there's no package for that architecture, so first i'll try to build it using qemu binaries to emulate the arm architecture on  x86_64 in order to make the build process faster (though if that fails i'll build it on a raspberry pi) and then i'm building it for x86_64. i'll let you know how it goes, i just imported your repo to my [GitLab account](https://gitlab.com/klud/dockerizing).

Cheers!

**Comment by pdonorio** [comment]
Very well, let me know!

**Comment by pdonorio** [comment]
Hey @klud1, I've got a reply that tells me how now there is an [official alpine package for rethinkdb](https://pkgs.alpinelinux.org/package/v3.5/community/x86_64/rethinkdb) that we didn't have one year ago.

There you can find the link to the build script in github.

I'll keep this issue open to remind to my self to create a new alpine docker image with the official package.

**Comment by ulm0** [comment]
Oh! Great! Yet no package for arm, i could learn to build packages for alpine and see if it works.

Thanks for letting me know!

**Comment by pdonorio** [comment]
Did you see [their alpine install script](https://git.alpinelinux.org/cgit/aports/tree/community/rethinkdb/APKBUILD?h=3.5-stable) to take inspiration?

**Comment by pdonorio** [comment]
Applied an automated build [here](https://hub.docker.com/r/pdonorio/rethinkdb/builds/)

**Comment by ulm0** [comment]
I'm trying to make some time now, college and work got me a bit busy :(
